// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCznXbxbnvyh2EQY31hposFZEr7wz8QCdw',
    appId: '1:603967572113:web:cf72b8e0310ea79ef21730',
    messagingSenderId: '603967572113',
    projectId: 'storify-app-2bd63',
    authDomain: 'storify-app-2bd63.firebaseapp.com',
    storageBucket: 'storify-app-2bd63.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA14DRqpxAv6jjeDuYMpiT-P3tgMyZwSgY',
    appId: '1:603967572113:android:53a90a68b6b84b7df21730',
    messagingSenderId: '603967572113',
    projectId: 'storify-app-2bd63',
    storageBucket: 'storify-app-2bd63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHx4TQ6OzDf2r5KSP1cVXQSdTATsPT1SQ',
    appId: '1:603967572113:ios:0cf70eac7aad5a2ef21730',
    messagingSenderId: '603967572113',
    projectId: 'storify-app-2bd63',
    storageBucket: 'storify-app-2bd63.firebasestorage.app',
    iosBundleId: 'com.example.flutterStoryApp',
  );
}
